spring:
  rabbitmq:
    host: 192.168.89.5
    port: 5672
    username: lm
    password: 2018
  application:
    name: spring-config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/liumeng0403/configs
          search-paths: demo2

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://mydal:1234@peer1:8001/eureka/,http://mydal:1234@peer2:8002/eureka/
    registry-fetch-interval-seconds: 5
