spring:
  application:
    name: service-a
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://peer1:9411
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 3
      min-idle: 1
      max-active: 5
      max-wait: 30000
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 3000000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      url: jdbc:mysql://192.168.89.4:3306/netflix_demo_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
      username: root
      password: local_ROOT@123_pwd

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://mydal:1234@peer1:8001/eureka/,http://mydal:1234@peer2:8002/eureka/
    registry-fetch-interval-seconds: 5

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl